schema_version: 1

context:
  version: "4.30.3"

package:
  name: firecrawl
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/firecrawl/firecrawl-${{ version }}.tar.gz
  sha256: 478b430e983ea43514bd89f0c4ffb043e64c19c29c9a024b5cf49c7f5d712b2c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - requests
    - httpx
    - python-dotenv
    - websockets
    - nest-asyncio
    - pydantic >=2.0
    - aiohttp

tests:
  - python:
      imports:
        - firecrawl
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Python SDK for Firecrawl API
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/firecrawl/firecrawl
  repository: https://github.com/firecrawl/firecrawl
  documentation: https://docs.firecrawl.dev

extra:
  recipe-maintainers:
    - moritzwilksch
